language: ruby
services:
- postgresql
rvm:
- 2.5.0

node_js:
- "node"

install:
- gem uninstall bundler
- gem install bundler --version '1.7.4'
- bundle install
- bundle exec rake db:create RAILS_ENV=test
- rake db:migrate

before_script:
- nvm install 14.2
- npm install eslint
- npm install @metahub/karma-jasmine-jquery
- npm install babel-eslint
- npm install eslint-plugin-jasmine
- npm install jasmine
- npm install jasmine-core
- npm install jasmine-jquery
- npm install karma
- npm install karma-chrome-launcher
- npm install karma-cli
- npm install karma-jasmine
- npm install karma-coverage
- npm install karma-spec-reporter
- npm install karma-jquery

script: 
- rake
- bundle exec rubocop
- node_modules/karma/bin/karma start karma.conf.js --single-run
# - node_modules/.bin/eslint **/*.js
- node -v
- npm run lint
