language: ruby
services:
- postgresql
rvm:
- 2.5.0
before_script:
  - npm install karma
install:
- gem uninstall bundler
- gem install bundler --version '1.7.4'
- bundle install
- bundle exec rake db:create RAILS_ENV=test
- rake db:migrate
script: 
- rake
- karma start karma.conf.js --single-run